miguelbel00/p-grupal

- MiguelFile.txt
DESCRIPTION
i modified miguels file for an example.
> |example| modified miguels file

- MiguelFile.txt
> [Example] modified miguel file

- MiguelFile.txt
- client/src/App.css
- client/src/App.js
- client/src/Pages/Register.jsx
- client/src/index.css
Como:Usuario
Quiero:Poder registrarme 
Para:Acceder a la pagina
> [Page:Register]:Create Register Page && And styles

- api/database/migrations/20221110005014-create-review.js
- api/database/models/Review.js
DESCRIPTION 
creando el modelo de reviews...
> [review] modelo creado

- api/database/migrations/20221110002942-create-transaction.js
- api/database/models/Transaction.js
- package.json
DESCRIPTION 
creando modelo de descripcion....
> [transactions] creando modelo

- client/src/App.js
- client/src/componets/NavBar.jsx
- client/src/styles/navbar.module.css
COMO: desarrollador
QUIERO: crear y darle estilos al navbar
PARA: poder navergar por la app
CAPTURA:
> [Navbar]: create navbar

- api/controllers/Product/getAllProduct.js
- api/database/models/Product.js
- api/database/models/Review.js
- api/database/seeders/20221111152012-create-products.js
- api/routes/productRoutes.js
AS developer 
I WANT get all products
FOR to use and to show
> [Product] routes all product GET

- client/src/Pages/Products.jsx
- client/src/componets/Filters.jsx
- client/src/redux/actions.js
- client/src/redux/reducer.js
- client/src/styles/home.css
AS: Developer
WANT: Order products
FOR: Show higher or minor price
> [Filter Order Products] Order Products

- api/database/seeders/2-create-categories.js
i changed the unique identfier because this is too longer and we don't need this security on this models
> [Models] change uuid for interget in  category, product and review models

- api/controllers/Product/getOneProduct.js
- api/routes/productRoutes.js
AS developer
I WANT get one product with all relationships
TO send data of one specific product
> [Routes] create route getOneProduct and is lacking review relationship

- client/src/Pages/Products.jsx
- client/src/componets/Filters.jsx
- client/src/redux/actions.js
- client/src/redux/reducer.js
COMO desarrollador
QUIERO poder filtrar los productos por categoria
PARA una mejor busqueda de producto
Evidencias del filtrado conbinando con ordenamiento
filtro de Perifericos ordenado por min-price
filtro de Componentes ordenado por max-price
> [FILTER]filter by categories of products

- api/database/seeders/3-create-products.js
AS developer
I WANT to update my seed
TO handle updated products.
> [Seed Product] updated product seed

- client/src/App.js
- client/src/Pages/Detail.jsx
- client/src/Pages/Products.jsx
- client/src/Pages/Register.jsx
- client/src/Pages/ShoppingCart.jsx
- client/src/Pages/home.jsx
- client/src/componets/Filters.jsx
- client/src/componets/NavBar.jsx
- client/src/redux/actions/actionShoppingCart.js
- client/src/redux/actions/actionsPetitions.js
- client/src/redux/reducers/reducerPetitions.js
- client/src/redux/store.js
> [REDUX] cambio de organizacion en las carpetas

- api/controllers/Product/createProduct.js
- api/database/migrations/2-create-User.js
- api/database/migrations/3-create-product.js
- api/database/models/Product.js
- api/database/seeders/2-create-categories.js
- api/database/seeders/3-create-products.js
- api/routes/index.js
- api/routes/productRoutes.js
COMO desarrollador
QUIERO poder crear productos
PARA poder manipularlo desde el front
#respuesta getOne Product
> [Product] create product POST

- api/database/seeders/1-create-users.js
- api/database/seeders/5-create-reviews.js
AS: Developer
I WANT: create reviews
TO: can show in the page
> [SEEDS] add reviews seeds

- client/src/Pages/Detail.jsx
- client/src/Pages/Products.jsx
- client/src/Pages/ShoppingCart.jsx
- client/src/componets/ItemCart.jsx
- client/src/redux/actions/actionShoppingCart.js
- client/src/redux/reducers/reducerShoppingCart.js
- client/src/redux/store.js
como: usuario
quiero: agregar productos al carrito 
para: efectuar una futura compra
> [Carrito] : create carrito page 

- api/controllers/Review/getAllReview.js
- api/routes/reviewRoutes.js
AS Admin
I WANT get all review
TO get the comments and the rating to calculate the most rate product
> [Review] add get All reviews Route

- api/database/migrations/3-create-product.js
- api/database/models/Product.js
- api/database/seeders/3-create-products.js
- client/src/componets/Filters.jsx
- client/src/redux/actions/actionsFilter.js
- client/src/redux/reducers/reducersFilter.js
As: Developer
Want: Order sales
For: show best seller/less sold
> [Order Sold] Filter and add model sold product

- api/controllers/Product/productEdit.js
- api/routes/productRoutes.js
As: Admin
Want: Edit products
For: Change name, price, stock, description and image
> [Edit Product] Add route product edit

- client/src/Pages/Detail.jsx
- client/src/Pages/Products.jsx
- client/src/componets/Filters.jsx
- client/src/componets/Paginated.jsx
- client/src/styles/Detail.css
> [Solution]: BUG pagianted and product detail 

- api/database/seeders/1-create-users.js
- api/database/seeders/2-create-categories.js
- api/database/seeders/4-create-productsCategory copy.js
COMO: desarrollador
QUIERO: optimizar las relaciones entre productos y categorías
PARA: poder utilizar los filtros correctamente
> [Products category] cambios en relaciones

- client/src/Pages/Products.jsx
- client/src/componets/Filters.jsx
- client/src/functions/functions.js
- client/src/redux/actions/actionsFilter.js
- client/src/redux/reducers/reducersFilter.js
description:
optimice y repare bugs en ordenamiento , cambie metodo de ordenamiento sort por quicksort que es mas eficaz, simplifique los ordenamientos por precio y mas vendidos a una sola accion , a un solo case en el reducer, quedando mas ordenado y funcional,
> [ordenamiento y filtrados , mejoras de codigo]

- api/controllers/Transaction/getAlltransaction.js
- api/routes/transactionRoutes.js
COMO desarrollador
QUIERO mostrar las transacciones
PARA poder ver si se hizo bien las transacciones.
> [Transactions] all transaction GET

- client/src/Pages/Detail.jsx
- client/src/componets/AddReview.jsx
- client/src/componets/Review.jsx
- client/src/componets/ReviewContainer.jsx
- client/src/redux/actions/actionsPetitions.js
- client/src/styles/addReview.module.css
COMO: desarrollador
QUIERO: crear el componente add review
PARA: que el cliente pueda añadir reviews a un producto
> [AddReview]

- api/controllers/User/userEdit.js
- client/src/App.js
- client/src/componets/CardUser.jsx
- client/src/componets/EditProfile.jsx
- client/src/componets/Profile.jsx
- client/src/redux/actions/actionsPetitions.js
- client/src/redux/reducers/reducerPetitions.js
- client/src/styles/carduser.module.css
- client/src/styles/editprofile.module.css
COMO usuario
QUIERO la opcion de editar mi perfil
PARA poder actualizar mis datos.
###
###
> [Update data ] Ari/F28

- api/controllers/Email/emailSend.js
- api/controllers/Paypal/orderCapture.js
- api/controllers/Paypal/orderCreate.js
- client/src/Pages/ShoppingCart.jsx
como: desarrollador
quiero: reducir y aumentar tanto el stock como los vendidos
para:  actualizar los datos
> [PASARELA]: agregado resta de stock y suma de vendidos 

- client/src/Pages/Detail.jsx
- client/src/Pages/Function.js
- client/src/Pages/Products.jsx
- client/src/Pages/ShoppingCart.jsx
- client/src/componets/AddReview.jsx
- client/src/componets/Footer.jsx
- client/src/styles/home.module.css
como: desarrollador
quiero: que el usuario no pueda comprar sin registrarse
para: evitar errores
> [SOLUTION BUG]: shoppingCart, Detail and Reviews

- client/src/componets/NavBar.jsx
- client/src/componets/SearchBar.jsx
- client/src/styles/searchBar.module.css
As: developer
Want: suggest products
for: see products
Create a new searchbar component, separate it from the nav bar
> [SearchBar] Suggestion Products

- client/src/componets/Filters.jsx
- client/src/styles/filters.module.css
> x en filtros
